In [1]:
import pandas as pd
import numpy as np
import os

# Defining the path

In [3]:
path = '/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data'

In [4]:
file_path = path + '/orders_products_prior.csv'

In [5]:
print(file_path)

/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv

# Sample for test

In [6]:
df = pd.read_csv(file_path, nrows=1000)
print(df.shape)
df.head()

(1000, 4)

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [7]:
df = pd.read_csv(file_path, low_memory=False)

In [8]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  int64
 3   reordered          int64
dtypes: int64(4)
memory usage: 989.8 MB

(32434489, 4)

# Loading Ords set

In [15]:
import os
print(os.getcwd())

/Users/mariatirado/Downloads

In [16]:
os.listdir()

['googlechrome.dmg',
 'Sexy+Upper+body+%281%29.pdf',
 '20250819_151804_Bewilligungsbescheid_Weiterbildungskosten.pdf',
 '~$Answers, E9 - Maria tirado.xlsx',
 '.DS_Store',
 'Maria Tirado - Sales & DA.pdf',
 '.localized',
 'googlechrome-2.dmg',
 'Phyton fundamentals',
 'Data bases and SQL',
 '1701032781228.jpeg',
 'TableauPublic-2025-2-0.dmg',
 '~$A4_final_report_template.xlsx',
 'Maria J Tirado - Sales & DA.pdf',
 'Anaconda3-2025.06-0-MacOSX-x86_64.pkg',
 'Sexy+Legs.pdf',
 'dbvis_macos-x64_25_2_4.dmg',
 '20250826_003515_Aufhebungsbescheid_und_Entgeltbescheinigung.pdf',
 '20250819_151804_AENDERUNGSBESCHEID.pdf',
 'Data visualization and story telling',
 '1712680251162.jpeg',
 '~$UK_Parent_HPV_Vaccine_Attitudes.xlsx',
 '.ipynb_checkpoints',
 'TableauAutoUpdate',
 'Microsoft_365_and_Office_16.100.25081015_BusinessPro_Installer.pkg',
 'RUDITH ANANCOIL RODRIGUEZ ALVAREZ, 23NOV 0150 LIMA.pdf',
 'Big+Booty.pdf',
 '20250819_151805_AENDERUNGSBESCHEID.pdf',
 'Intro to Data Analysis',
 '4',
 '07-2024 Instacart Basket Analysis',
 'Cuerpo+de+pera.pdf']

In [17]:
import os
os.listdir()

['googlechrome.dmg',
 'Sexy+Upper+body+%281%29.pdf',
 '20250819_151804_Bewilligungsbescheid_Weiterbildungskosten.pdf',
 '~$Answers, E9 - Maria tirado.xlsx',
 '.DS_Store',
 'Maria Tirado - Sales & DA.pdf',
 '.localized',
 'googlechrome-2.dmg',
 'Phyton fundamentals',
 'Data bases and SQL',
 '1701032781228.jpeg',
 'TableauPublic-2025-2-0.dmg',
 '~$A4_final_report_template.xlsx',
 'Maria J Tirado - Sales & DA.pdf',
 'Anaconda3-2025.06-0-MacOSX-x86_64.pkg',
 'Sexy+Legs.pdf',
 'dbvis_macos-x64_25_2_4.dmg',
 '20250826_003515_Aufhebungsbescheid_und_Entgeltbescheinigung.pdf',
 '20250819_151804_AENDERUNGSBESCHEID.pdf',
 'Data visualization and story telling',
 '1712680251162.jpeg',
 '~$UK_Parent_HPV_Vaccine_Attitudes.xlsx',
 '.ipynb_checkpoints',
 'TableauAutoUpdate',
 'Microsoft_365_and_Office_16.100.25081015_BusinessPro_Installer.pkg',
 'RUDITH ANANCOIL RODRIGUEZ ALVAREZ, 23NOV 0150 LIMA.pdf',
 'Big+Booty.pdf',
 '20250819_151805_AENDERUNGSBESCHEID.pdf',
 'Intro to Data Analysis',
 '4',
 '07-2024 Instacart Basket Analysis',
 'Cuerpo+de+pera.pdf']

In [18]:
import glob

matches = glob.glob('/Users/mariatirado/Downloads/**/orders*.csv', recursive=True)
print(matches)

['/Users/mariatirado/Downloads/4/orders.csv', '/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv', '/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/4/orders.csv']

In [19]:
import os
import pandas as pd

# Project root and folders
project = '/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis'
prepared = os.path.join(project, '02 Data', 'Prepared Data')

df_ords = None
for fname in ['orders_wrangled.csv', 'orders_cleaned.csv']:
    fpath = os.path.join(prepared, fname)
    if os.path.exists(fpath):
        print('Found:', fpath)
        df_ords = pd.read_csv(fpath)
        break

if df_ords is None:
    raise FileNotFoundError('No cleaned orders file found in Prepared Data.')

df_ords.head()

FileNotFoundError: No cleaned orders file found in Prepared Data.

In [20]:
import os
os.getcwd()

'/Users/mariatirado/Downloads'

In [23]:
import os

for root, dirs, files in os.walk('.', topdown=False):
    for name in files:
        if 'orders_cleaned.csv' in name:
            print(os.path.join(root, name))

In [24]:
import os

os.chdir('/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Prepared Data')
print("✅ Current directory set to:", os.getcwd())

✅ Current directory set to: /Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Prepared Data

In [25]:
os.listdir()

[]

In [26]:
import os, glob

patterns = [
    '/Users/mariatirado/**/orders_cleaned.csv',
    '/Users/mariatirado/**/orders_wrangled.csv'
]

matches = []
for p in patterns:
    matches.extend(glob.glob(p, recursive=True))

print("Found:", len(matches), "match(es)")
for m in matches:
    print(m)

Found: 2 match(es)
/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_cleaned.csv
/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_wrangled.csv

In [27]:
import pandas as pd

df_ords = pd.read_csv('/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_cleaned.csv')
df_ords.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [28]:
df = pd.read_csv('/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv', low_memory=False)
df.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [29]:
df_merged = df_ords.merge(df, on='order_id', indicator=True)
df_merged['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

# Checking match

In [31]:
df_merged = df_ords.merge(df, on='order_id', indicator=True)

In [32]:
df_merged['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

# Check the output

In [34]:
df_merged[df_merged['_merge'] != 'both']

Empty DataFrame
Columns: [order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order, product_id, add_to_cart_order, reordered, _merge]
Index: []

In [35]:
import pandas as pd

df_ords_prior = pd.read_csv('/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv', low_memory=False)

In [36]:
df_ords_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [37]:
df_ords = pd.read_csv('/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_cleaned.csv')

In [38]:
df_ords.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [39]:
df_merged = df_ords.merge(df_ords_prior, on='order_id', indicator=True)
df_merged['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

In [40]:
df_ords_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [41]:
df_ords_prior.shape

(32434489, 4)

In [42]:
df_ords.shape

(3421083, 7)

In [43]:
df_merged_large = df_ords.merge(df_ords_prior, on = 'order_id', indicator = True)

In [45]:
df_merged_large.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,prior,1,2,8,NaN,196,1,0,both
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both

In [46]:
df_merged_large['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

In [1]:
df_merged_large = df_ords.merge(df_ords_prior, on='order_id', how='outer', indicator=True)

NameError: name 'df_ords' is not defined

In [48]:
df_merged_large['_merge'].value_counts()

_merge
both          32434489
left_only       206209
right_only           0
Name: count, dtype: int64

In [49]:
import os

path = '/Users/mariatirado/29-10-2025 Instacart Basket Analysis/02 Data/Prepared Data'

# Export as pickle
df_merged_large.to_pickle(os.path.join(path, 'orders_products_combined.pkl'))

print("✅ Pickle file saved successfully!")

✅ Pickle file saved successfully!

In [51]:
import pandas as pd

df_check = pd.read_pickle('/Users/mariatirado/29-10-2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_products_combined.pkl')
df_check.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,1,112108,train,4,4,10,9.0,NaN,NaN,NaN,left_only
1,2,202279,prior,3,5,9,8.0,33120.0,1.0,1.0,both
2,2,202279,prior,3,5,9,8.0,28985.0,2.0,1.0,both
3,2,202279,prior,3,5,9,8.0,9327.0,3.0,0.0,both
4,2,202279,prior,3,5,9,8.0,45918.0,4.0,1.0,both

# Correction: Re-export Inner Merge Versions (as requested)

In [2]:
import os
import pandas as pd

In [3]:
path = '/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data'

In [4]:
file_path = path + '/orders_products_prior.csv'

In [5]:
print(file_path)

/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv

In [6]:
import os
print(os.getcwd())

/Users/mariatirado/29-10-2025 Instacart Basket Analysis/03 Scripts

In [7]:
os.listdir()

['4.5 Data Consistency Checks',
 '4.3 Intro to Pandas.ipynb',
 '4.3 IC Data import and descriptive analysis',
 '4.6.2 Combining & Exporting Data.ipynb',
 '4.2 Importing libraries and Python data types.ipynb',
 '4.4 Data Wrangling & Subsetting',
 '.ipynb_checkpoints',
 '4.6 Combining & Exporting Data.ipynb']

In [8]:
import os
os.listdir()

['4.5 Data Consistency Checks',
 '4.3 Intro to Pandas.ipynb',
 '4.3 IC Data import and descriptive analysis',
 '4.6.2 Combining & Exporting Data.ipynb',
 '4.2 Importing libraries and Python data types.ipynb',
 '4.4 Data Wrangling & Subsetting',
 '.ipynb_checkpoints',
 '4.6 Combining & Exporting Data.ipynb']

In [9]:
import glob

matches = glob.glob('/Users/mariatirado/Downloads/**/orders*.csv', recursive=True)
print(matches)

['/Users/mariatirado/Downloads/4/orders.csv', '/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv', '/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/4/orders.csv']

In [11]:
import os
os.getcwd()

'/Users/mariatirado/29-10-2025 Instacart Basket Analysis/03 Scripts'

In [12]:
import os

for root, dirs, files in os.walk('.', topdown=False):
    for name in files:
        if 'orders_cleaned.csv' in name:
            print(os.path.join(root, name))

In [13]:
import os

os.chdir('/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Prepared Data')
print("✅ Current directory set to:", os.getcwd())

✅ Current directory set to: /Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Prepared Data

In [14]:
os.listdir()

[]

In [15]:
import os, glob

# look for either name
patterns = [
    '/Users/mariatirado/**/orders_cleaned.csv',
    '/Users/mariatirado/**/orders_wrangled.csv'
]

matches = []
for p in patterns:
    matches.extend(glob.glob(p, recursive=True))

print("Found:", len(matches), "match(es)")
for m in matches:
    print(m)

Found: 2 match(es)
/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_cleaned.csv
/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_wrangled.csv

In [16]:
import pandas as pd

df_ords = pd.read_csv('/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_cleaned.csv')
df_ords.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [17]:
df = pd.read_csv('/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv', low_memory=False)
df.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [18]:
df_merged = df_ords.merge(df, on='order_id', indicator=True)
df_merged['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

In [19]:
import pandas as pd

df_ords_prior = pd.read_csv('/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/orders_products_prior.csv', low_memory=False)

In [20]:
df_ords_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [21]:
df_ords = pd.read_csv('/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_cleaned.csv')

In [22]:
df_ords.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [23]:
df_merged_large = df_ords.merge(df_ords_prior, on = 'order_id', indicator = True)

In [24]:
df_merged_large.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,prior,1,2,8,NaN,196,1,0,both
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both

In [25]:
df_merged_large['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

In [26]:
df_merged_large['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

In [27]:
import os

# Define where you want to save it
path = '/Users/mariatirado/29-10-2025 Instacart Basket Analysis/02 Data/Prepared Data'

# Export as pickle
df_merged_large.to_pickle(os.path.join(path, 'orders_products_combined_2.pkl'))

print("✅ Pickle file saved successfully!")

✅ Pickle file saved successfully!