In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import scipy

# Importing Customer dataset

In [3]:
path = r'/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis'

In [4]:
customers = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'customers.csv'))

In [5]:
customers.shape

(206209, 10)

In [6]:
customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

# Renaming columns

In [10]:
customers.rename(columns={
    'First Name': 'first_name',
    'Surnam': 'last_name',
    'gender': 'gender',
    'STATE': 'state',
    'Age': 'age',
    'date_joined': 'date_joined',
    'n_dependants': 'number_of_dependents',
    'fam_status': 'family_status',
    'income': 'income'}, inplace=True)

In [11]:
customers.head()

,user_id,first_name,last_name,gender,state,age,date_joined,number_of_dependents,family_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

# Droping columns that don’t add analytical value

In [12]:
customers = customers.drop(columns=['first_name', 'last_name', 'date_joined'])

In [13]:
customers.head()

,user_id,gender,state,age,number_of_dependents,family_status,income
0,26711,Female,Missouri,48,3,married,165665
1,33890,Female,New Mexico,36,0,single,59285
2,65803,Male,Idaho,35,2,married,99568
3,125935,Female,Iowa,40,0,single,42049
4,130797,Female,Maryland,26,1,married,40374

# Comments
first_name and last_name aren’t useful for analysis or merging

date_joined might not be relevant unless you’re studying tenure

# Fundamental data quality and consistency checks

In [14]:
# Count missing values per column
customers.isnull().sum()

user_id                 0
gender                  0
state                   0
age                     0
number_of_dependents    0
family_status           0
income                  0
dtype: int64

# Comment
no missing values

In [15]:
# Count duplicates
customers.duplicated().sum()

np.int64(0)

# Comment
no duplicates

In [16]:
# Check for mixed data types
customers.dtypes

user_id                  int64
gender                  object
state                   object
age                      int64
number_of_dependents     int64
family_status           object
income                   int64
dtype: object

# Comment
No mixed data types

In [17]:
# Statistic check

customers.describe()

             user_id            age  number_of_dependents         income
count  206209.000000  206209.000000         206209.000000  206209.000000
mean   103105.000000      49.501646              1.499823   94632.852548
std     59527.555167      18.480962              1.118433   42473.786988
min         1.000000      18.000000              0.000000   25903.000000
25%     51553.000000      33.000000              0.000000   59874.000000
50%    103105.000000      49.000000              1.000000   93547.000000
75%    154657.000000      66.000000              3.000000  124244.000000
max    206209.000000      81.000000              3.000000  593901.000000

# Comment
looks completely clean and realistic

In [18]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206209 entries, 0 to 206208
Data columns (total 7 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   user_id               206209 non-null  int64
 1   gender                206209 non-null  object
 2   state                 206209 non-null  object
 3   age                   206209 non-null  int64
 4   number_of_dependents  206209 non-null  int64
 5   family_status         206209 non-null  object
 6   income                206209 non-null  int64
dtypes: int64(4), object(3)
memory usage: 11.0+ MB

In [19]:
customers.describe(include='all')

,user_id,gender,state,age,number_of_dependents,family_status,income
count,206209.000000,206209,206209,206209.000000,206209.000000,206209,206209.000000
unique,NaN,2,51,NaN,NaN,4,NaN
top,NaN,Male,Idaho,NaN,NaN,married,NaN
freq,NaN,104067,4044,NaN,NaN,144906,NaN
mean,103105.000000,NaN,NaN,49.501646,1.499823,NaN,94632.852548
std,59527.555167,NaN,NaN,18.480962,1.118433,NaN,42473.786988
min,1.000000,NaN,NaN,18.000000,0.000000,NaN,25903.000000
25%,51553.000000,NaN,NaN,33.000000,0.000000,NaN,59874.000000
50%,103105.000000,NaN,NaN,49.000000,1.000000,NaN,93547.000000
75%,154657.000000,NaN,NaN,66.000000,3.000000,NaN,124244.000000
max,206209.000000,NaN,NaN,81.000000,3.000000,NaN,593901.000000

# Summary of what I’ve done

Checked and handled missing data

Removed duplicates

Converted mixed data types

Corrected potential outliers

Exported a clean version for merging

In [21]:
import os

In [22]:
path = r'/Users/mariatirado/29-10-2025 Instacart Basket Analysis'

In [23]:
customers.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'customers_cleaned.pkl'))

# Combining the customer data with the rest of the prepared Instacart data

In [24]:
import pandas as pd
import os

In [25]:
path = r'/Users/mariatirado/29-10-2025 Instacart Basket Analysis'

In [26]:
# Main prepared Instacart data (the newest one with flags)
ords = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data',
                                   'ords_prods_merge_spending_frequency.pkl'))

In [27]:
ords.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,day_type,busiest_days_new,busiest_period_of_day,max_order,loyalty_flag,spending_flag,spending_mean,median_days,frequency_flag
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer
1,2539329,1,prior,1,2,8,NaN,14084,2,0,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer
2,2539329,1,prior,1,2,8,NaN,12427,3,0,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer
3,2539329,1,prior,1,2,8,NaN,26088,4,0,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer
4,2539329,1,prior,1,2,8,NaN,26405,5,0,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer

In [28]:
ords.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', 'price_range_loc', 'day_type',
       'busiest_days_new', 'busiest_period_of_day', 'max_order',
       'loyalty_flag', 'spending_flag', 'spending_mean', 'median_days',
       'frequency_flag'],
      dtype='object')

In [29]:
# Cleaned customers file (from your last step)
customers = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data',
                                        'customers_cleaned.pkl'))

In [30]:
customers.head()

,user_id,gender,state,age,number_of_dependents,family_status,income
0,26711,Female,Missouri,48,3,married,165665
1,33890,Female,New Mexico,36,0,single,59285
2,65803,Male,Idaho,35,2,married,99568
3,125935,Female,Iowa,40,0,single,42049
4,130797,Female,Maryland,26,1,married,40374

# Making sure the join keys match in type

In [31]:
ords['user_id'] = ords['user_id'].astype('int64', errors='ignore')
customers['user_id'] = customers['user_id'].astype('int64', errors='ignore')

# Ensuring one row per user in customers

In [32]:
# If any duplicates slipped in, keep the first
customers = customers.drop_duplicates(subset='user_id')

# Merge on user_id

In [33]:
ords_cust = ords.merge(customers, on='user_id', how='left')

# Quick check

In [34]:
ords.shape, customers.shape, ords_cust.shape

((32432460, 24), (206209, 7), (32432460, 30))

In [36]:
ords_cust[['gender','state','age','number_of_dependents','family_status','income']].isna().mean().round(3)

gender                  0.0
state                   0.0
age                     0.0
number_of_dependents    0.0
family_status           0.0
income                  0.0
dtype: float64

# Exporting

In [37]:
import os

# Define your main project path
path = r'/Users/mariatirado/29-10-2025 Instacart Basket Analysis'

# Export the merged dataset as a pickle file
ords_cust.to_pickle(os.path.join(
    path, '02 Data', 'Prepared Data', 'ords_prods_customers_merged.pkl'))

print("✅ File successfully saved in '02 Data/Prepared Data' as ords_prods_customers_merged.pkl")

✅ File successfully saved in '02 Data/Prepared Data' as ords_prods_customers_merged.pkl