In [1]:
import pandas as pd
import numpy as np 
import os

# 01 Defining path

In [5]:
path = os.getcwd()

# 02 importing data set

In [8]:
df_dep = pd.read_csv(r'/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/departments.csv', index_col=False)

In [10]:
df_dep.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

# 03 Transposing df_dep

In [11]:
df_dep.T

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [12]:
df_dep_t = df_dep.T

In [13]:
df_dep_t

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [14]:
df_dep_t.reset_index()

            index                0
0   department_id       department
1               1           frozen
2               2            other
3               3           bakery
4               4          produce
5               5          alcohol
6               6    international
7               7        beverages
8               8             pets
9               9  dry goods pasta
10             10             bulk
11             11    personal care
12             12     meat seafood
13             13           pantry
14             14        breakfast
15             15     canned goods
16             16       dairy eggs
17             17        household
18             18           babies
19             19           snacks
20             20             deli
21             21          missing

# 04 Create a new header

In [15]:
new_header = df_dep_t.iloc[0]

In [16]:
new_header

0    department
Name: department_id, dtype: object

# 05 Delete the first row

In [17]:
df_dep_t_new = df_dep_t[1:]

In [18]:
df_dep_t_new

                  0
1            frozen
2             other
3            bakery
4           produce
5           alcohol
6     international
7         beverages
8              pets
9   dry goods pasta
10             bulk
11    personal care
12     meat seafood
13           pantry
14        breakfast
15     canned goods
16       dairy eggs
17        household
18           babies
19           snacks
20             deli
21          missing

# 06 Set new header

In [20]:
df_dep_t_new.columns = new_header

In [21]:
df_dep_t_new

department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

# 07 Data dictionary

In [22]:
data_dict = df_dep_t_new.to_dict('index')

In [23]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [25]:
df_prods = pd.read_csv(r'/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/4/products.csv', index_col=False)

In [26]:
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [27]:
print(data_dict.get('19'))

{'department': 'snacks'}

In [28]:
df_snacks =  df_prods[df_prods['department_id']==19]

In [29]:
df_prods['department_id']==19

0         True
1        False
2        False
3        False
4        False
         ...
49688    False
49689    False
49690    False
49691    False
49692    False
Name: department_id, Length: 49693, dtype: bool

In [30]:
df_prods[df_prods['department_id']==19]

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5
...,...,...,...,...,...
49666,49662,Bacon Cheddar Pretzel Pieces,107,19,3.6
49669,49665,Super Dark Coconut Ash & Banana Chocolate Bar,45,19,6.9
49670,49666,Ginger Snaps Snacking Cookies,61,19,5.2
49675,49671,Milk Chocolate Drops,45,19,3.0
49683,49679,Famous Chocolate Wafers,61,19,6.0

In [31]:
df_snacks =  df_prods[df_prods['department_id']==19]

In [32]:
df_snacks.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5

# 08 Find another identifier variable in the df_ords dataframe that doesn’t need to be included

In [34]:
df_ords = pd.read_csv(r'/Users/mariatirado/Downloads/07-2024 Instacart Basket Analysis/02 Data/Original Data/4/orders.csv', index_col=False)

In [36]:
df_ords

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [37]:
df_ords['user_id'] = df_ords['user_id'].astype('object')

In [38]:
df_ords.dtypes

order_id                    int64
user_id                    object
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

# In the df_ords dataframe, user_id is another identifier variable that does not need to be included in numerical analysis. I changed its data type from numeric (int64) to object

# 09 Look for a variable in your df_ords dataframe with an unintuitive name and change its name without overwriting the dataframe.

In [39]:
df_ords_renamed = df_ords.rename(columns={'order_dow': 'order_day_of_week'}, inplace=False)

In [40]:
df_ords_renamed.head()
df_ords_renamed.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_day_of_week',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')

# The variable order_dow was unintuitive because the abbreviation “dow” isn’t immediately clear. It represents the day of the week when an order was placed, so I renamed it to order_day_of_week for clarity.

# 10 The busiest hour for placing orders

In [41]:
df_ords['order_hour_of_day'].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [42]:
df_ords['order_hour_of_day'].value_counts().idxmax()

np.int64(10)

In [43]:
df_ords['order_hour_of_day'].value_counts().max()

288418

# The busiest hour for placing orders is around 10:00 AM, based on the frequency distribution of the order_hour_of_day variable.

# 11 Determine the meaning behind a value of 4 in the "department_id" column within the df_prods dataframe using a data dictionary.

In [44]:
print(data_dict.get('4'))

{'department': 'produce'}

# 12 The sales team in your client’s organization wants to know more about breakfast item sales. Create a subset containing only the required information.

In [45]:
df_breakfast =  df_prods[df_prods['department_id']==14]

In [46]:
df_breakfast

,product_id,product_name,aisle_id,department_id,prices
27,28,Wheat Chex Cereal,121,14,10.1
33,34,NaN,121,14,12.2
67,68,"Pancake Mix, Buttermilk",130,14,13.7
89,90,Smorz Cereal,121,14,3.9
210,211,Gluten Free Organic Cereal Coconut Maple Vanilla,130,14,3.6
...,...,...,...,...,...
49330,49326,Cereal Variety Fun Pack,121,14,9.1
49395,49391,Light and Fluffy Buttermilk Pancake Mix,130,14,2.0
49547,49543,Chocolate Cheerios Cereal,121,14,10.8
49637,49633,Shake 'N Pour Buttermilk Pancake Mix,130,14,14.2
49667,49663,Ultra Protein Power Crunch Peanut Butter N' Ho...,57,14,10.2

# 13 Products that customers might use to throw dinner parties

In [49]:
party_ids = [5, 7, 12, 20]
dinner_party_prods = df_prods[df_prods['department_id'].isin(party_ids)].copy()

In [50]:
dinner_party_prods

,product_id,product_name,aisle_id,department_id,prices
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
6,7,Pure Coconut Water With Orange,98,7,4.4
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4
10,11,Peach Mango Juice,31,7,2.8
16,17,Rendered Duck Fat,35,12,17.1
...,...,...,...,...,...
49676,49672,Cafe Mocha K-Cup Packs,26,7,6.5
49679,49675,Cinnamon Dolce Keurig Brewed K Cups,26,7,14.0
49680,49676,Ultra Red Energy Drink,64,7,14.5
49686,49682,California Limeade,98,7,4.3
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3

# 14 How many rows does the last dataframe you created have?

In [51]:
dinner_party_prods.shape

(7650, 5)

# 15 "user_id" of “1”, Extract all the information you can about this user

In [52]:
user_1 = df_ords[df_ords['user_id'] == 1]

In [53]:
user_1

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0
10,1187899,1,train,11,4,8,14.0

# 16 What basic stats can you provide based on the information you have?

In [54]:
user_1.describe()

,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,1.100000e+01,11.000000,11.000000,11.000000,10.000000
mean,1.923450e+06,6.000000,2.636364,10.090909,19.000000
std,1.071950e+06,3.316625,1.286291,3.477198,9.030811
min,4.315340e+05,1.000000,1.000000,7.000000,0.000000
25%,8.690170e+05,3.500000,1.500000,7.500000,14.250000
50%,2.295261e+06,6.000000,3.000000,8.000000,19.500000
75%,2.544846e+06,8.500000,4.000000,13.000000,26.250000
max,3.367565e+06,11.000000,4.000000,16.000000,30.000000

In [60]:
print(os.path.join(path, '02 Data', 'Prepared Data'))

/Users/mariatirado/29-10-2025 Instacart Basket Analysis/03 Scripts/4.4 Data Wrangling & Subsetting/02 Data/Prepared Data

In [61]:
import os

path = r'/Users/mariatirado/29–10–2025 Instacart Basket Analysis'   # <- project root
os.makedirs(os.path.join(path, '02 Data', 'Prepared Data'), exist_ok=True)

df_ords.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_wrangled.csv'), index=False)

In [62]:
test = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_wrangled.csv'))
test.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [63]:
import os
file_path = os.path.join(path, '02 Data', 'Prepared Data', 'orders_wrangled.csv')
print(os.path.exists(file_path))
print(file_path)

True
/Users/mariatirado/29–10–2025 Instacart Basket Analysis/02 Data/Prepared Data/orders_wrangled.csv

In [64]:
df_dep_t_new.to_csv(os.path.join(path, '02 Data', 'Prepared Data', 'departments_wrangled.csv'), index=False)

In [65]:
import os
os.listdir(os.path.join(path, '02 Data', 'Prepared Data'))

['orders_wrangled.csv', 'departments_wrangled.csv']